version: 2.0
jobs:
  test:
    machine:
        image: cimg/php:7.1.33
    steps:
      - checkout
      - run:
          name: CI Setup
          command: sudo ./build-scripts/ciSetup.sh
      - run:
          name: Run Tests
          command: npm run ci-test

workflows:
  version: 2

  btd:
    jobs:
      - test
